name: registro_tgo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  face_camera: ^0.1.0
  flutter:
    sdk: flutter
  image: ^4.1.7
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tfmodel/
